# 생물정보학 및 실습 1 - Term Project용 Mission 3 환경 셋업

```
생물정보학 및 실습 1
서울대학교 생물정보학전공/생명과학부 2026년 1학기

이 노트북은 Creative Commons BY-SA 조건으로 재사용 가능합니다.
장혜식 <hyeshik@snu.ac.kr>, 서울대학교 생명과학부
```

이 노트북은 Google Colab을 이용해서 Term Project를 할 수 있도록 환경을 준비해 줍니다. 터미널 사용이 원활하지 않은 상태이고, 데이터를 오랫동안 보관하기 어렵기 때문에 되도록 개인용 컴퓨터에서 [Anaconda](https://www.anaconda.com/)나 [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) 등을 설치하고 사용하시는 것이 편하지만, 개인용 컴퓨터 사양이 부족한 경우에는 Google CoLab을 사용할 수도 있습니다. 개인용 컴퓨터를 쓸 때는 Windows에서는 [WSL2](https://docs.microsoft.com/en-us/windows/wsl/install-win10)를 쓰시면 리눅스 커맨드라인 환경을 쓸 수 있습니다. Google Colab은 창을 닫은 후 90분 후, 또는 창을 처음 열고 12시간 후에 환경을 닫아버리기 때문에 매번 실습할 때마다 새로 셋업이 필요합니다. `Runtime->Run All`을 실행해서 전체를 한 번 실행하시면 준비됩니다. 모든 것이 잘 안 되고 뭔가 꼬인 느낌이 강하게 들 때는 `Runtime->Factory reset runtime`을 누르고 새로 시작하시면 될 수도 있습니다.

## Google Drive 마운트

데이터 파일들을 불러오고 저장하기 위해서 Google Drive를 연결합니다. **이번엔 스크립트 파일을 편집해야 하기 때문에 Google Drive 마운트를 하지 않으면 vim등 콘솔에서 쓸 수 있는 에디터를 쓰셔야 합니다.** 화면에 나오는 주소를 눌러서 인증하고 인증 코드를 그 아래에 입력하세요. 그러면 `/contents/drive/MyDrive`에서 자신의 Drive 최상단 폴더가 보입니다. Google CoLab에서 접속하지 않고, 본인 컴퓨터 또는 연구실 워크스테이션 등 다른 컴퓨터를 쓰시는 경우에는 저장공간이 충분하므로 이 부분은 생략하고 지나갑니다.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## 실습용 Bioconda 환경 설치하기
Google CoLab에서 접속하지 않고, 본인 컴퓨터 또는 연구실 워크스테이션 등 다른 컴퓨터를 쓰시는 경우에는 따로 실습용 [Bioconda](https://bioconda.github.io/) 환경을 구축해서 이 노트북을 그 환경 안에서 띄우시면 됩니다.

CoLab을 쓰시는 분들은 다음에 따라서 실습용 프로그램들을 쉽게 설치할 수 있도록 [Bioconda](https://bioconda.github.io/) 환경을 만듭니다. 실행하고 진행상황을 관찰하다가 에러로 보이는 것이 있으면 잘 읽어보고 해결합니다.

파이썬 모듈들은 Colab쪽의 파이썬 인터프리터를 바꿀 수 없기 때문에 Conda에 설치하더라도 사용하기 어렵습니다. 파이썬 모듈은 `pip` 명령어로 설치하시면 Colab에서 불러와서 사용할 수 있습니다.

환경 초기화에 관련된 스크립트는 [GitHub 프로젝트](https://github.com/hyeshik/colab-biolab)에 있습니다.

In [ ]:
cd ./drive/MyDrive/Colab_Notebooks/BI_lecture1/colab-biolab/

/content/drive/MyDrive/Colab_Notebooks/BI_lecture1/colab-biolab

In [ ]:
!pwd

/content/drive/MyDrive/Colab_Notebooks/BI_lecture1/colab-biolab

In [ ]:

!bash tools/setup.sh
exec(open('tools/activate_conda.py').read())

tar: ./root/.bashrc.biolab: file changed as we read it
tar: ./root/.condarc: file changed as we read it
tar: ./root/.profile: file changed as we read it
tar: ./root/.tmux.conf: file changed as we read it
./
./root/
./root/.bashrc.biolab
./root/.bin.priority/
./root/.bin.priority/pip
./root/.bin.priority/pip2
./root/.bin.priority/pip3
./root/.condarc
./root/.profile
./root/.tmux.conf
tar: ./root/.vimrc: file changed as we read it
tar: ./root: file changed as we read it
./root/.vimrc
PREFIX=/root/conda
Unpacking bootstrapper...
Unpacking payload...

Installing base environment...

Preparing transaction: ...working... done
Executing transaction: ...working... done
installation finished.
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda3: /root/conda
Activated conda environment `lab'!

In [ ]:
cd ../

/content/drive/MyDrive/Colab_Notebooks/BI_lecture1

설정이 끝났으면, 이제 콘솔을 열어서 터미널로 접속할 수 있는 통로를 열어줍니다.

## 시퀀싱 데이터 다운로드
***첫 실습 시간에 데이터 복사를 마쳤으면 이 부분은 생략하고 지나갑니다.***

이제 실습 수업에서 필요한 시퀀싱 데이터를 다운로드 받아서 설치합시다. 드라이브 공간만 충분하면 데이터는 계속 저장돼 있기 때문에 학기 전체를 통해서 딱 한 번만 하시면 됩니다. Colab에서는 작업용 데이터를 Google Drive 폴더 아래의 `binfo-datapack1`에 저장합니다. 실습용 데이터는 `/content/drive/MyDrive/binfo1-datapack1`에 풀리게 됩니다.

### (Option 1) Google CoLab에서 접속한 경우
1. [Google Drive 공유폴더](https://drive.google.com/drive/folders/1QBJednh-C7A17PFOlpZHBKyDmBvd6klh?usp=sharing)에 접속합니다.
1. 중간 제목줄의 "binfo1-datapack1 ▾"에서 ▾을 누릅니다.
1. Add shortcut to Drive를 누릅니다.
1. My Drive를 선택해서 ADD SHORTCUT 버튼을 누릅니다.
1. 다음 cell을 실행해서 링크가 제대로 들어왔는지 확인합니다. (바로 확인되지 않으면 3–5분 정도 기다렸다가 하면 됩니다.)
1. 제대로 확인되면 다음으로 넘어갑니다.

In [ ]:
!ls -al /content/drive/MyDrive/binfo1-datapack1/

### (Option 2) CoLab외의 다른 환경에서 접속한 경우
본인 컴퓨터나 연구실 워크스테이션 등에서 작업하는 경우에는 다음 명령어로 다운로드 받으시면 됩니다. 첫 번째에는 wget이 접속오류를 내는 경우가 많으니, 접속에러가 발생하면 다시 한 번 실행해 보세요. `/content/drive/Mydrive` 부분은 원하는 저장 경로로 바꿔서 지정하시면 됩니다.

In [ ]:
!wget -O - --no-check-certificate https://hyeshik.qbio.io/binfo/binfo1-datapack1.tar | tar -C /content/drive/MyDrive -xf -

### 파일 체크섬 확인
***첫 실습 시간에 데이터 복사를 마쳤으면 이 부분은 생략하고 지나갑니다.***

받은 데이터의 MD5 체크섬을 확인합니다. 한참 걸립니다. 각 파일들의 원래 체크섬은 다음과 같습니다. 한 번 비교해 보세요.

```
140aaf30bcb9276cc716f8699f04ddd6  CLIP-35L33G.bam
f1b3336ed7e2f97d562dcc71641251bd  CLIP-35L33G.bam.bai
328883a73d507eafbf5b60bd6b906201  RNA-control.bam
02073818e2f398a73c3b76e5169de1ca  RNA-control.bam.bai
b09550d09d6c2a4ce27f0226f426fdb1  RNA-siLin28a.bam
fef112c727244060ea62d3f2564a07f6  RNA-siLin28a.bam.bai
28bbd0c47d725669340c784f1b772c01  RNA-siLuc.bam
43590fdc4d81905c0432e0d1cb8cfd5b  RNA-siLuc.bam.bai
5c08a9297307bc83259e658c4474f0cc  RPF-siLin28a.bam
a1bb3e29be412dfd7fd8d16b1b1acc4c  RPF-siLin28a.bam.bai
f2eebf50943024d0116c9cd3e744c707  RPF-siLuc.bam
dc24f69e8f571fc8be30f28ce5b84fcd  RPF-siLuc.bam.bai
```

In [ ]:
!md5sum drive/MyDrive/binfo1-datapack1/*

In [ ]:
!ls -al drive/MyDrive/binfo*

# 파일 복사하기
***첫 실습 시간에 데이터 복사를 마쳤으면 이 부분은 생략하고 지나갑니다.***

공유한 폴더를 나의 작업 폴더로 복사합니다.

In [ ]:
!mkdir -p /content/drive/MyDrive/binfo1-work
%cd /content/drive/MyDrive/binfo1-work
!cp ../binfo1-datapack1/* .

/content/drive/MyDrive/binfo1-work
^C

# 프로그램 설치
**첫 실습 시간에 데이터 복사를 마쳤으면 여기부터 시작합니다.**

데이터 준비가 끝났으면, 이제 이번 시간 실습에 필요한 프로그램들 몇 가지를 추가로 설치합니다.

In [ ]:
!conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
!conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

accepted Terms of Service for https://repo.anaconda.com/pkgs/main
accepted Terms of Service for https://repo.anaconda.com/pkgs/r

In [ ]:
!conda install -y bedtools bioawk samtools

Jupyter detected...
2 channel Terms of Service accepted
Retrieving notices: - \ | done
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | done
Solving environment: - \ | done

## Package Plan ##

  environment location: /root/conda

  added / updated specs:
    - bedtools
    - bioawk
    - samtools


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bedtools-2.31.1            |       h13024bc_3         1.5 MB  bioconda
    bioawk-1.0                 |      h577a1d6_13         198 KB  bioconda
    ca-certificates-2026.4.22  |       hbd8a1cb_0         128 KB  conda-forge
    conda-26.3.2               |  py313h78bf25f_1         1.2 MB  conda-forge
    htslib-1.23.1              |       h633afcb_0         1.1 MB  bioconda
    libdeflate-1.25            |       h17f619e_0          72 KB  conda-forge
    liblzma-5.8.2              |       hb03c661_0         111 KB  conda-forge
    openssl-3.6.2              |       h35e630c_0         3.0 MB  conda-forge
    samtools-1.23.1            |       ha83d96e_0         479 KB  bioconda
    ------------------------------------------------------------
                                           Total:         7.9 MB

The following NEW packages will be INSTALLED:

  bedtools           bioconda/linux-64::bedtools-2.31.1-h13024bc_3
  bioawk             bioconda/linux-64::bioawk-1.0-h577a1d6_13
  htslib             bioconda/linux-64::htslib-1.23.1-h633afcb_0
  libdeflate         conda-forge/linux-64::libdeflate-1.25-h17f619e_0
  liblzma            conda-forge/linux-64::liblzma-5.8.2-hb03c661_0
  samtools           bioconda/linux-64::samtools-1.23.1-ha83d96e_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main/linux-64::ca-certificates-2~ --> conda-forge/noarch::ca-certificates-2026.4.22-hbd8a1cb_0
  conda              pkgs/main::conda-26.3.2-py313h06a4308~ --> conda-forge::conda-26.3.2-py313h78bf25f_1
  openssl               pkgs/main::openssl-3.5.6-h1b28b03_0 --> conda-forge::openssl-3.6.2-h35e630c_0



Downloading and Extracting Packages:
openssl-3.6.2        | 3.0 MB    | :   0% 0/1 [00:00<?, ?it/s]
bedtools-2.31.1      | 1.5 MB    | :   0% 0/1 [00:00<?, ?it/s]

conda-26.3.2         | 1.2 MB    | :   0% 0/1 [00:00<?, ?it/s]


htslib-1.23.1        | 1.1 MB    | :   0% 0/1 [00:00<?, ?it/s]



samtools-1.23.1      | 479 KB    | :   0% 0/1 [00:00<?, ?it/s]




bioawk-1.0           | 198 KB    | :   0% 0/1 [00:00<?, ?it/s]





ca-certificates-2026 | 128 KB    | :   0% 0/1 [00:00<?, ?it/s]






liblzma-5.8.2        | 111 KB    | :   0% 0/1 [00:00<?, ?it/s]







openssl-3.6.2        | 3.0 MB    | :   2% 0.020692753841922845/1 [00:00<00:04,  4.84s/it]
bedtools-2.31.1      | 1.5 MB    | :   6% 0.06114855072013018/1 [00:00<00:01,  1.64s/it]


htslib-1.23.1        | 1.1 MB    | :  21% 0.20557759726164215/1 [00:00<00:00,  2.05it/s]

conda-26.3.2         | 1.2 MB    | :  13% 0.1307064402279704/1 [00:00<00:00,  1.28it/s]



samtools-1.23.1      | 479 KB    | :   3% 0.033437075888529476/1 [00:00<00:03,  3.32s/it]



samtools-1.23.1      | 479 KB    | : 100% 1.0/1 [00:00<00:00,  3.32s/it]


htslib-1.23.1        | 1.1 MB    | : 100% 1.0/1 [00:00<00:00,  2.05it/s]

openssl-3.6.2        | 3.0 MB    | :  84% 0.843229719058356/1 [00:00<00:00,  4.91it/s]
bedtools-2.31.1      | 1.5 MB    | : 100% 1.0/1 [00:00<00:00,  5.70it/s]
bedtools-2.31.1      | 1.5 MB    | : 100% 1.0/1 [00:00<00:00,  5.70it/s]






liblzma-5.8.2        | 111 KB    | :  14% 0.14472603284249208/1 [00:00<00:01,  1.38s/it]





ca-certificates-2026 | 128 KB    | :  13% 0.12503147917795465/1 [00:00<00:01,  1.61s/it]





ca-certificates-2026 | 128 KB    | : 100% 1.0/1 [00:00<00:00,  1.61s/it]






liblzma-5.8.2        | 111 KB    | : 100% 1.0/1 [00:00<00:00,  1.38s/it]




bioawk-1.0           | 198 KB    | :   8% 0.08078337787332235/1 [00:00<00:02,  2.68s/it]







libdeflate-1.25      | 72 KB     | :  22% 0.2229418968567152/1 [00:00<00:00,  1.00it/s]




bioawk-1.0           | 198 KB    | : 100% 1.0/1 [00:00<00:00,  2.68s/it]







openssl-3.6.2        | 3.0 MB    | : 100% 1.0/1 [00:00<00:00,  4.91it/s]



samtools-1.23.1      | 479 KB    | : 100% 1.0/1 [00:00<00:00,  3.72it/s]



samtools-1.23.1      | 479 KB    | : 100% 1.0/1 [00:00<00:00,  3.72it/s]


htslib-1.23.1        | 1.1 MB    | : 100% 1.0/1 [00:00<00:00,  2.56it/s]


htslib-1.23.1        | 1.1 MB    | : 100% 1.0/1 [00:00<00:00,  2.56it/s]

conda-26.3.2         | 1.2 MB    | : 100% 1.0/1 [00:00<00:00,  1.67it/s]

conda-26.3.2         | 1.2 MB    | : 100% 1.0/1 [00:00<00:00,  1.67it/s]





ca-certificates-2026 | 128 KB    | : 100% 1.0/1 [00:00<00:00,  1.76it/s]





ca-certificates-2026 | 128 KB    | : 100% 1.0/1 [00:00<00:00,  1.76it/s]






liblzma-5.8.2        | 111 KB    | : 100% 1.0/1 [00:00<00:00,  1.69it/s]






liblzma-5.8.2        | 111 KB    | : 100% 1.0/1 [00:00<00:00,  1.69it/s]




bioawk-1.0           | 198 KB    | : 100% 1.0/1 [00:00<00:00,  1.56it/s]




bioawk-1.0           | 198 KB    | : 100% 1.0/1 [00:00<00:00,  1.56it/s]







libdeflate-1.25      | 72 KB     | : 100% 1.0/1 [00:00<00:00,  1.47it/s]







openssl-3.6.2        | 3.0 MB    | : 100% 1.0/1 [00:00<00:00,  4.91it/s]





































Preparing transaction: - done
Verifying transaction: | / - done
Executing transaction: | done

## Mission 3

이번 미션에서는 Figure S2A 아랫쪽에 표시되는 clustered error 분석 (CIMS; Crosslinking-induced mutation sites)을 합니다. 자외선에 의해서 단백질이 붙어있다가 단백질 분해효소로 단백질을 뜯어내고 남은 자리에서는 reverse-transcriptase가 오류를 자주 냅니다. 오류율을 분석해서 단백질이 앉아 있었던 자리를 분석해 봅시다.

데이터는 지난 번과 동일하기 때문에 이미 다운로드 받으셨다면 다시 다운로드 받을 필요는 없습니다.

In [ ]:
%cd /content/drive/MyDrive/Colab_Notebooks/BI_lecture1/binfo1-work/

/content/drive/MyDrive/Colab_Notebooks/BI_lecture1/binfo1-work

Genome 전체로 계산하는 방법은 자원도 꽤 쓰고 시간이 걸리기 때문에 여기서는 유전자 단위로 간략하게 하도록 합시다. 예시로 Mirlet7g를 해 보고, 추가로 Mirlet7f-1과 Mirlet7d도 봐서 비교해 봅시다.

논문은 예전 레퍼런스 유전체인 mm9을 쓰고 있기 때문에, 현재 사용되는 레퍼런스 mm39와는 좌표계에 차이가 있습니다. 새로 annotation에서 위치를 찾습니다.

In [ ]:
!grep -i mirlet7d ../binfo1-datapack1/gencode.gtf

chr13	ENSEMBL	gene	48689488	48689590	.	-	.	gene_id "ENSMUSG00000065453.3"; gene_type "miRNA"; gene_name "Mirlet7d"; level 3; mgi_id "MGI:2676796";
chr13	ENSEMBL	transcript	48689488	48689590	.	-	.	gene_id "ENSMUSG00000065453.3"; transcript_id "ENSMUST00000083519.3"; gene_type "miRNA"; gene_name "Mirlet7d"; transcript_type "miRNA"; transcript_name "Mirlet7d-201"; level 3; transcript_support_level "NA"; mgi_id "MGI:2676796"; tag "basic";
chr13	ENSEMBL	exon	48689488	48689590	.	-	.	gene_id "ENSMUSG00000065453.3"; transcript_id "ENSMUST00000083519.3"; gene_type "miRNA"; gene_name "Mirlet7d"; transcript_type "miRNA"; transcript_name "Mirlet7d-201"; exon_number 1; exon_id "ENSMUSE00000522678.2"; level 3; transcript_support_level "NA"; mgi_id "MGI:2676796"; tag "basic";

위 결과에서 gtf 파일이 없다고 나오면 압축이 풀리지 않은 상태일 수 있으니, 미리 풀어서 작업해보세요.

Splicing 되지 않는 transcript이기 때문에 결과가 단조롭습니다. 해당 좌표 범위로 bam을 솎아냅니다.

In [ ]:
!samtools view -b -o CLIP-let7d.bam ../binfo1-datapack1/CLIP-35L33G.bam chr13:48689488-48689590
!samtools view CLIP-let7d.bam | wc -l

samtools: /root/conda/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /root/conda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /root/conda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /root/conda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /root/conda/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /root/conda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /root/conda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /root/conda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
187

각 자리에 mapping된 read들의 분포를 요약하기 위해 samtools mpileup을 이용합니다. Shannon entropy를 구할 때는 reference를 따로 줄 필요는 없습니다. samtools를 쓰지 않고 직접 read를 분석하면 더욱 더 재미있습니다.

In [ ]:
!samtools mpileup CLIP-let7d.bam > CLIP-let7d.pileup
!wc -l CLIP-let7d.pileup

samtools: /root/conda/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /root/conda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /root/conda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /root/conda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
[mpileup] 1 samples in 1 input files
87 CLIP-let7d.pileup

Mirlet7g는 100bp도 안 되는 짧은 gene인데 `mpileup` 결과는 엄청 길게 나옵니다. 왜 그럴까요? (잘 한 번 생각해 봅시다)

이제 Mirlet7g의 핵심부분을 살펴봐서 어떻게 하면 좋을지 견적을 내 봅니다.

In [ ]:
!head CLIP-let7d.pileup

chr13	48689488	N	24	^Ga^Ia^Ha^Ia^Ha^Ia^Ia^Ia^Ga^Ia^Ia^Ia^Ia^Ia^Ha^Ia^Ga^Ga^Ga^Ia^Ea^Da^Ha^Ga	BIHGGIHIEIIIGIHIGEGH5BDD
chr13	48689489	N	53	aaaaaaaaaaaaaaaaaaaaaaaaa^Ia^Ha^Ia^Ga^Ga^Ha^Ia^Ia^Ga^Ga^Ia^Ia^Ha^Ia^Ia^Ha^Ha^Da^Ia^Ha^Ia^Ia^Ia^Ia^Ia^Ha^Ga^Ga	GIHIGIIIEIIIIIHIG>EB4@5HDIHIBEGIID?IIGII@H>IGHIIIGHDC
chr13	48689490	N	69	ttttttttttttttttttttttttttttttttttttttttttttttttttttt^Gt^Gt^Ht^Gt^It^It^Ht^It^Gt^Gt^Ht^It^It^It^Ht^It	GIHIGHIFFIIIIIFHGEDG;2>FDIHIDGBIIDBIIDIIAH>IBGIIIGHBG=BG=IIGIDGHFIIHI
chr13	48689491	N	105	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa^Ia^Ia^Ha^Ga^Ia^Ga^Ia^Ga^Ha^Ha^Ha^Ga^Ia^Ha^Ha^Ia^@a^Ia^Ia^Ia^Ga^Ha^Ha^Ga^Ha^Ga^Ia^Ha^Ga^Ia^Ga^Ha^Ga^Ia^Ia^Ga	EIGHEHHIEIIIIIHIGCBH:?>HGGHI>GBIIGBIIGIHBB;IHIIIIGHDC3=G:IGGIDEHIFIGHII=GIDHEGHHEIGGI7III9=HGBAIGBIGFG>I2
chr13	48689492	N	105	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa	GIGIEIEI7IIIGIGIG;?F:D@G7GHIAGAIIG3IIGIHDB2IHIIIIDDGC1<GCIIHIGCHIIIEIIIGCIBIEGHH?HHFI9IIIA=GGB?IEGIFEGGIA
chr13	48689493	N	105	ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg	BIEIGHGI7IHHGIGHG=?F58>E5EHIAGAHIDAHIGII:EDHHIHIIGG>>5EDAIIFFGDHIIHGIII8EIDIBBHHBIGHI7HII?=GGBEIG>HFEGGIA
chr13	48689494	N	105	ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg	FIFEGIFE3HFIGIGHG=?D1?@D5EHIAEADIBFIIGHIBD<IHDGIIGBD>03GEEIHF@DHIIIDIIHEAIDIC>HHBHFDI9FIIE=GGBAIGEFEEGIIA
chr13	48689495	N	104	cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc	GID>GHEG.HIHGH>IG2;B;?>E0BCI8G?FGA?HH@HIB?DHBIIIHGBG90BAEIEF8CEDIHGIIHGAI?I3BGH;HHHE7IIIA=GG:?IFEBF2GBI;
chr13	48689496	N	102	cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc	FI8EEGEI.GEB<ID>G38B19>BFFI<D<FGAEFIGDFB@@CH>EHH8B7>BDCEEEBBCHBGEEFHIG?I;IG@HH2EEGI9IIIA>;<@IE<E:CDIG<
chr13	48689497	N	104	cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc	DIHFBIFG.HIIFIGIB3;B993E:IGHAGDIDC3IIHDIBDHBIIIII>;58?A>IIEHBAHBHIGHIEFBI0BG<HHEEGDG.III?7H?>3IE<H8EDGG?

In [ ]:
!awk '$2 >= 48689488 && $2 <= 48689590 { print $0; }' CLIP-let7d.pileup > CLIP-let7d-gene.pileup
!tail CLIP-let7d-gene.pileup

chr13	48689565	N	6	cccccc	>IGIIH
chr13	48689566	N	6	tttttt	:IGFIH
chr13	48689567	N	6	aaaaaa	8IFIFI
chr13	48689568	N	6	cccccc	?IGIII
chr13	48689569	N	6	tttttt	;IGIII
chr13	48689570	N	5	aaaaa	EDECD
chr13	48689571	N	6	cccccc	:GGIGG
chr13	48689572	N	6	cccccc	:GGIGG
chr13	48689573	N	6	tttttt	5GGIGG
chr13	48689574	N	6	c$c$c$c$c$c$	;GGIGG

이제 pandas에 불러와서 분석해 봅니다. R을 쓰시는 분들은 R로 보내서 작업하셔도 됩니다.

In [ ]:
import pandas as pd

pileup = pd.read_csv('CLIP-let7d-gene.pileup', sep='\t', names=['chrom', 'pos', '_ref', 'count', 'basereads', 'quals'])
pileup.tail()

    chrom       pos _ref  count     basereads   quals
82  chr13  48689570    N      5         aaaaa   EDECD
83  chr13  48689571    N      6        cccccc  :GGIGG
84  chr13  48689572    N      6        cccccc  :GGIGG
85  chr13  48689573    N      6        tttttt  5GGIGG
86  chr13  48689574    N      6  c$c$c$c$c$c$  ;GGIGG

여기서 pileup에서 계산에 사용할 것은 match와 substitution만입니다. 나머지에 해당하는 tag들은 제거합니다.

R을 쓰시는 분들은 R로 보내서 작업하셔도 됩니다.

In [ ]:
import re
toremove = re.compile('[<>$*#^]')
pileup['matches'] = pileup['basereads'].apply(lambda x: toremove.sub('', x))

In [ ]:
pileup[['chrom', 'pos', 'matches']]

    chrom       pos                                            matches
0   chr13  48689488   GaIaHaIaHaIaIaIaGaIaIaIaIaIaHaIaGaGaGaIaEaDaHaGa
1   chr13  48689489  aaaaaaaaaaaaaaaaaaaaaaaaaIaHaIaGaGaHaIaIaGaGaI...
2   chr13  48689490  tttttttttttttttttttttttttttttttttttttttttttttt...
3   chr13  48689491  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
4   chr13  48689492  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
..    ...       ...                                                ...
82  chr13  48689570                                              aaaaa
83  chr13  48689571                                             cccccc
84  chr13  48689572                                             cccccc
85  chr13  48689573                                             tttttt
86  chr13  48689574                                             cccccc

[87 rows x 3 columns]

In [ ]:
pileup[pileup['pos'] == 48689488].iloc[0]['matches']

'GaIaHaIaHaIaIaIaGaIaIaIaIaIaHaIaGaGaGaIaEaDaHaGa'

처리하는 도중에 matches에서 뜻밖의 예외상황이 있을 수 있습니다.
예외상황 중 결과에 영향을 미치지 않는 패턴은 미리 제거하고 처리하면 편리합니다.

자 이제 데이터 준비가 대충 끝났습니다. 다음 순서로 진행해 보세요. (1-4번 단계는 R을 쓰시는 분들은 R로 보내서 작업하셔도 됩니다.)

1. 각 position별로 base수를 셉니다.
1. 각 position별로 Shannon entropy를 계산합니다.
1. 계산한 Shannon entropy를 [bedgraph format](https://genome.ucsc.edu/goldenPath/help/bedgraph.html)으로 출력합니다. 말은 복잡해도 실제로는 간단합니다. 4칸짜리를 만드시면 됩니다.
1. 결과 파일을 본인의 Google Drive에서 가져옵니다.
1. [UCSC Genome Browser](http://genome.ucsc.edu/cgi-bin/hgTracks?db=mm39&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr9%3A106056039-106056126)에 접속해서 Genome은 mm39로 선택합니다.
1. 그래프 아랫쪽의 add custom tracks 버튼을 누릅니다.
1. Paste URLs or data 옆의 Choose File 버튼을 누르고 우리가 만든 bedgraph 파일을 업로드 합니다.
1. 그리고 이리 저리 감상해 보다가 View 메뉴의 PDF/PS 를 눌러서 인증샷을 한 번 찍습니다.
1. Mirlet7d와 Mirlet7f-1도 한 번 해 봅니다.

In [ ]:
import numpy as np
from collections import Counter
import math

def calculate_entropy(sequence):
    if not sequence:
        return 0
    counts = Counter(sequence)
    total = sum(counts.values())
    probs = [count / total for count in counts.values()]
    return -sum(p * math.log2(p) for p in probs if p > 0)

# 1 & 2. 각 위치별 Shannon entropy 계산
pileup['entropy'] = pileup['matches'].apply(calculate_entropy)

# 3. bedGraph format (chrom, start, end, value) 생성
# bedGraph는 0-based start, 1-based end를 사용하므로 pos-1을 start로 잡습니다.
bedgraph = pileup[['chrom', 'pos', 'entropy']].copy()
bedgraph['start'] = bedgraph['pos'] - 1
bedgraph['end'] = bedgraph['pos']
bedgraph = bedgraph[['chrom', 'start', 'end', 'entropy']]

# 결과 저장
output_filename = '/content/drive/MyDrive/Colab_Notebooks/BI_lecture1/mission3_bedgraph/mirlet7d.bedgraph'
bedgraph.to_csv(output_filename, sep='\t', header=False, index=False)
print(f'{output_filename} has been created.')

/content/drive/MyDrive/Colab_Notebooks/BI_lecture1/mission3_bedgraph/mirlet7d.bedgraph has been created.

In [ ]:
display(bedgraph.head(20))

    chrom     start       end   entropy
0   chr13  48689487  48689488  1.906454
1   chr13  48689488  48689489  1.499800
2   chr13  48689489  48689490  0.988811
3   chr13  48689490  48689491  1.258637
4   chr13  48689491  48689492 -0.000000
5   chr13  48689492  48689493 -0.000000
6   chr13  48689493  48689494 -0.000000
7   chr13  48689494  48689495 -0.000000
8   chr13  48689495  48689496 -0.000000
9   chr13  48689496  48689497 -0.000000
10  chr13  48689497  48689498 -0.000000
11  chr13  48689498  48689499 -0.000000
12  chr13  48689499  48689500 -0.000000
13  chr13  48689500  48689501  0.563000
14  chr13  48689501  48689502  1.184668
15  chr13  48689502  48689503  0.656280
16  chr13  48689503  48689504 -0.000000
17  chr13  48689504  48689505 -0.000000
18  chr13  48689505  48689506 -0.000000
19  chr13  48689506  48689507 -0.000000

In [ ]:
# 분석에 사용한 코드와 결과로 얻은 그림 (인증샷) 모두 GitHub repository에 업로드 해 주세요.